### ISSUE TITLE
Fix bug in code

### ISSUE THREAD

**Issue by khazin** [kerenteo/capstone#1]
Hi I found a bug in your code and I would like to provide a solution.

**Comment by kerenteo** [comment]
Hey, May I know where is the bug? TIA

**Comment by khazin** [comment]
Your code is sending email to the 1st recipient only instead of all recipients. 
At line 30. $mail->addAddress($addr[0]);  change to $mail->addAddress($addr[$i]);

**Comment by kerenteo** [comment]
Resolved. Able to send multiple mails now. Thank you
